# docker-compose.yml
version: '3.8'

services:
  server:
    build:
      context: ./
      dockerfile: Server.Dockerfile
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
  client:
    build:
      context: ./
      dockerfile: Client.Dockerfile
    ports:
      - '3030:3030'
    environment:
      NODE_ENV: production
