# docker-compose.yml
version: '3.8'

services:
  server:
    image: codeeditor-server
    platform: linux/amd64
    container_name: codeeditor-server
    build:
      context: ./
      dockerfile: Server.Dockerfile
    ports:
      - '3000:3000'
    environment:
      - PUBLIC_LIVE_API_KEY=APIECBzrnxEjXE3
      - PUBLIC_LIVE_API_SECRET=SkEWmGIJR56FZu5pnLnSLxPDHpagbddjZliNPOHT0iK
      - PUBLIC_LIVE_WEBSOCKET_URL=wss://codeeditor-341m5dwl.livekit.cloud
      - DATABASE_URL=mysql://root:cc5428486@codeeditor-mysql:3306/codeeditor
    depends_on:
      - mysql
    networks:
      - net1
  mysql:
    image: mysql:latest
    platform: linux/amd64
    container_name: codeeditor-mysql
    restart: always
    environment:
      - MYSQL_DATABASE=codeeditor
      - MYSQL_ROOT_PASSWORD=cc5428486
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - net1
  client:
    image: codeeditor-client
    platform: linux/amd64
    container_name: codeeditor-client
    build:
      context: ./
      dockerfile: Client.Dockerfile
    ports:
      - '3030:80'
    networks:
      - net1
    environment:
      - PUBLIC_LIVE_API_KEY=APIECBzrnxEjXE3
      - PUBLIC_LIVE_API_SECRET=SkEWmGIJR56FZu5pnLnSLxPDHpagbddjZliNPOHT0iK
      - PUBLIC_LIVE_WEBSOCKET_URL=wss://codeeditor-341m5dwl.livekit.cloud
      - DATABASE_URL=mysql://root:root@localhost:3306/codeeditor
    depends_on:
      - server

volumes:
  mysql-data:
    driver: local

networks:
  net1:
    driver: bridge