# docker-compose.yml
version: '3.8'

services:
  server:
    image: pdy666/codeeditor-server
    # build:
    #   context: ./
    #   dockerfile: Server.Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env.server
    environment:
      NODE_ENV: production
    depends_on:
      - mysql
    command: sh -c '/wait-for mysql:3306 -- node /app/server/dist/apps/server/src/main.js'
    networks:
      - net1
  mysql:
    platform: linux/amd64
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=code
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - net1
  client:
    image: pdy666/codeeditor-client
    # build:
    #   context: ./
    #   dockerfile: Client.Dockerfile
    ports:
      - '3030:80'
    networks:
      - net1
    env_file:
      - .env.client
    environment:
      NODE_ENV: production
    depends_on:
      - server

volumes:
  mysql-data:
    driver: local

networks:
  net1:
    driver: bridge